steps:

- name: gcr.io/cloud-builders/docker
  id: build
  entrypoint: bash
  args:
  - -c
  - |
    docker build . -t arrisar/php:latest -t arrisar/php:8.0

- name: gcr.io/cloud-builders/docker
  id: push
  entrypoint: bash
  args:
  - -c
  - |
    docker push arrisar/php:latest;
    docker push arrisar/php:8.0